### PR TITLE
Add pre to releaseTypes #58

### PR DESCRIPTION
**Pull request by marianojabdala**

### CODE REVIEW

**Comment by jhartman86** [comment]
@webpro i'm running into an issue with this as well. anything I can do to help get this released to NPM?

**Comment by msegado** [comment]
I believe the exposed command should actually be `prerelease` rather than `pre`, as described in the `node-semver` README: https://github.com/npm/node-semver#functions

There is [an internal `pre` command](https://github.com/npm/node-semver/blob/d21444a0658224b152ce54965d02dbe0856afb84/semver.js#L449), but it's not part of their documented public api so it's probably not a good idea to use it (though amusingly it looks like it exactly satisfies @StephanBijzitter's use case over in #56).

(Also, it looks like there was a typo in the docs that references a non-existent "`prelease`" command; might be a good idea to delete it if/when you switch from `pre` to `prerelease` to avoid confusion...)

**Comment by StephanBijzitter** [comment]
As for the documentation in the `pre` command linked above, this indeed is exactly what I would like to use. :-)

**Comment by webpro** [comment]
Released in v2.5.0.

**Pull request closed without merging**
