### PR TITLE
Add documentation for NPM OTP usage

### PR DESCRIPTION
**Pull request by lgraubner**
I had to look through the issues for this information, might be useful to have in the README.

### CODE REVIEW

**Comment by webpro** [comment]
Hi, @lgraubner! Very useful to add indeed. Please use lower-cased "npm". Also, the release-it process doesn't fail if the OTP isn't provided, it asks for it, so that should be reworded a bit. Thanks!

**Comment by webpro** [comment]
I've just tried again, and it WOMM™... Also through an npm script.

Did you run it in non-interactive mode (`-n`)?

**Comment by wilzbach** [comment]
I ran into this with -n, but it would be great if this worked with -n as I don't want to reanswer settings that stay the same all the time.

**Comment by webpro** [comment]
As [2FA/OTP has been added to the readme](https://github.com/webpro/release-it#two-factor-authentication), I'm closing this issue. Feel free to re-open or open a new ticket to discuss this.

**Pull request closed without merging**
